// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Gunpla struct {
	ID              string `json:"id"`
	BoxArtImageLink string `json:"boxArtImageLink"`
	Title           string `json:"title"`
	Subtitle        string `json:"subtitle"`
	Classification  string `json:"classification"`
	LineupNo        string `json:"lineupNo"`
	Scale           string `json:"scale"`
	Franchise       string `json:"franchise"`
	ReleaseDate     string `json:"releaseDate"`
	JanIsbn         string `json:"janIsbn"`
	Run             string `json:"run"`
	Price           string `json:"price"`
	Includes        string `json:"includes"`
	Features        string `json:"features"`
}
